//{{NO_DEPENDENCIES}}
// Включаемый файл, созданный в Microsoft Visual C++.
// Используется NCTestProj.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_FIRST_FORM                  101
#define IDD_LEFT_BAR                    102
#define IDR_MAINFRAME                   128
#define IDD_TRAIN_FORM                  130
#define IDD_BOTTOM_BAR                  131
#define IDD_RIGHT_BAR                   132
#define IDB_SVET_OFF                    133
#define IDB_SVET_RED                    134
#define IDB_SVET_YEL                    135
#define IDB_SVET_GREEN                  136
#define IDD_PROGRESS_DLG                139
#define IDD_KEY_DLG                     140
#define IDB_ASTERIX                     142
#define IDB_WARNING                     143
#define IDD_TST_DLG                     145
#define IDD_PSW_DLG                     146
#define IDD_BURDEN_DLG                  147
#define IDB_GERBBLUE                    151
#define IDI_PATH                        152
#define IDI_PATH_2                      153
#define IDI_ICON2                       154
#define IDC_MANUAL_BTN                  1000
#define IDC_TRAIN_BTN                   1001
#define IDC_TEST_BTN                    1002
#define IDC_EXIT_BTN                    1003
#define IDC_IMAGE_LIST                  1004
#define IDC_DELIMAGE_BTN                1005
#define IDC_CLEARLIST_BTN               1006
#define IDC_ADD_BTN                     1007
#define IDC_LEARN_BTN                   1008
#define IDC_CHECK_BTN                   1009
#define IDC_OUTPUTTEXT                  1009
#define IDC_CLEAR_BTN                   1010
#define IDC_CHECK1                      1010
#define IDC_CHECK2                      1011
#define IDC_CHECK3                      1012
#define IDC_CHECK4                      1013
#define IDC_CHECK5                      1014
#define IDC_CHECK6                      1015
#define IDC_CHECK7                      1016
#define IDC_EDIT1                       1017
#define IDC_EDIT2                       1018
#define IDC_EDIT3                       1019
#define IDC_EDIT4                       1020
#define IDC_STATIC_R                    1021
#define IDC_CODE_BTN                    1022
#define IDC_CLOSE_BTN                   1024
#define IDC_SECRET_RADIO                1025
#define IDC_PUBLIC_RADIO                1026
#define IDC_STATIC01                    1028
#define IDC_STATIC02                    1029
#define IDC_STATIC1                     1030
#define IDC_STATIC2                     1031
#define IDC_STOP_BTN                    1032
#define IDC_FINAL_STATIC                1033
#define IDC_STATIC_GB                   1034
#define IDC_GENKEY_BTN                  1035
#define IDC_MAINPSWTAB                  1036
#define IDC_garm                        1036
#define IDC_STATIC_N                    1039
#define IDC_STATIC_C                    1040
#define IDC_LOGIN_EDIT                  1041
#define IDC_PSW_EDIT                    1043
#define IDC_STATIC_GB1                  1046
#define IDC_STATIC_GB2                  1047
#define IDC_LOAD_BTN                    1048
#define IDC_START_BTN                   1049
#define IDC_PROGRESS1                   1050
#define IDC_SHOWRES_BTN                 1052
#define IDC_PROGRESS_BAR                1053
#define IDC_EXEC_STATIC                 1054
#define IDC_EXEC_ST                     1055
#define IDC_BUTTON1                     1056
#define IDC_MCD_BTN                     1056
#define IDC_SLIDER1                     1057
#define IDC_linear                      1064
#define IDC_linear2                     1065
#define ID__USESIGN                     32770
#define ID__NOTUSESIGN                  32771
#define ID_SET_PSW                      32772
#define ID_TRAIN_NET                    32773
#define ID_TEST_NET                     32774
#define ID_LOAD_IMAGES                  32775
#define ID_SAVE_IMAGES                  32776
#define ID_TESTON_TI                    32777
#define ID_TESTON_WN                    32778
#define ID_CHECK_ALL                    32779
#define ID_OBVODKA                      32780
#define ID_PROVERKA                     32781
#define ID_LOAD_BDTI                    32782
#define ID_BURDEN                       32801
#define ID_Menu                         32802
#define ID_32803                        32803
#define ID_CRACKING                     32804
#define ID_32805                        32805
#define ID_STABILITY                    32806
#define ID_32807                        32807
#define ID_TI_MULTIPLICATION            32808
#define ID_32809                        32809
#define ID_MORFING                      32810
#define ID_32811                        32811
#define ID_GRWIDTH                      32812

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1065
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
